### ISSUE TITLE
Always 'Searching for: "exception"'.

### ISSUE THREAD

**Issue by axit-joost** [stefanbauer/ignition-laracasts-tab#1]
No matter what type of error, it always ends up 'Searching for: "exception"', yielding the same result.

**Comment by bobbybouwmann** [comment]
@axit-joost Thanks for creating an issue! It seems that I can't reproduce your case. Could be more specific about what kind of exception your throwing?

This is an example of what I see
<img width="1336" alt="Screenshot 2019-09-04 at 22 38 49" src="https://user-images.githubusercontent.com/5872362/64289639-e2303480-cf64-11e9-9246-9e32e7fb3e55.png">

**Comment by bobbybouwmann** [comment]
@axit-joost So it seems something went wrong with compiling the correct assets and pushing that in the release. We releases a new version v0.2.0 which should fix this for you! 

Let me know if you have any troubles after updating to the new version :)
